"""``templates scaffold``: write a new template's skeleton (EXPLORER_TEMPLATES.md §2.2).

Writes ``template.json`` (status ``unvalidated``) plus a ``plugin.py`` and
``test_<slug>.py`` whose shape depends on ``kind``:

* ``department`` — a :class:`~enterprise_sim.archetypes._base.DepartmentArchetypeSpec`
  registered via ``ARCHETYPES.register(...)``, running an existing built-in
  playbook (``build_software``) so it needs no new authoring to be valid.
* ``playbook`` — a minimal declarative SDK playbook (one ``OnStart`` process)
  registered via the ``_PlaybookPlugin``/``_ProcessPlugin`` pattern
  ``enterprise_sim/playbooks/build_software.py`` uses.
* ``bundle`` — both: a department archetype whose own new playbook it runs.

Every scaffolded template is written to validate green out of the box
(``templates validate`` immediately after ``templates scaffold`` is the
acceptance test, EXPLORER_TEMPLATES.md §5) — that is what keeps this module
honest as the reference the author-playbook agent's first draft imitates.
"""

from __future__ import annotations

import re
from pathlib import Path

from enterprise_sim.templates.store import (
    Template,
    TemplateKind,
    now_iso,
    template_dir,
    write_template,
)

_SLUG_RE = re.compile(r"^[a-z][a-z0-9_]*$")


def _validate_slug(slug: str) -> None:
    if not _SLUG_RE.match(slug):
        raise ValueError(
            f"slug {slug!r} must be lowercase, start with a letter, and contain only "
            "letters, digits, and underscores"
        )


def _title(slug: str) -> str:
    return slug.replace("_", " ").title()


def _pascal(slug: str) -> str:
    return "".join(part.title() for part in slug.split("_"))


def _department_plugin(slug: str, description: str) -> str:
    title = _title(slug)
    charter = description or f"Run the {title} department."
    return f'''"""The "{title}" department archetype template.

Generated by ``enterprise-sim templates scaffold --kind department``
(EXPLORER_TEMPLATES.md §2.2). Edit freely — re-check with
``enterprise-sim templates validate --dir <templates-dir> --slug {slug}``.
"""

from __future__ import annotations

from enterprise_sim.archetypes._base import DepartmentArchetypeSpec, TeamShape
from enterprise_sim.core.registry import ARCHETYPES

#: The {title} department archetype.
{slug.upper()} = ARCHETYPES.register(
    DepartmentArchetypeSpec(
        name="{slug}",
        charter={charter!r},
        typical_goals=(
            "Ship {{project}} to general availability.",
        ),
        team_shapes=(
            TeamShape(title="{title} Core", count="2..5", skills=("generalist",)),
        ),
        # References an existing built-in playbook by name — a template may
        # reuse any registered playbook without authoring a new one.
        playbooks=("build_software",),
    )
)
'''


def _department_test(slug: str) -> str:
    return f'''"""Tests for the "{slug}" department archetype template."""

from __future__ import annotations

from pathlib import Path

from enterprise_sim.core.registry import discover_paths


def test_{slug}_archetype_registers() -> None:
    from enterprise_sim.core.registry import ARCHETYPES

    discover_paths([Path(__file__).resolve().parent.parent])
    assert "{slug}" in ARCHETYPES
    spec = ARCHETYPES.get("{slug}")
    assert spec.playbooks
'''


def _playbook_plugin(slug: str, description: str) -> str:
    title = _title(slug)
    pascal = _pascal(slug)
    return f'''"""The "{title}" playbook template.

Generated by ``enterprise-sim templates scaffold --kind playbook``
(EXPLORER_TEMPLATES.md §2.2). Edit freely — re-check with
``enterprise-sim templates validate --dir <templates-dir> --slug {slug}``.

{description or f"A minimal playbook for the {title} scenario."}
"""

from __future__ import annotations

from collections.abc import Callable, Sequence
from dataclasses import dataclass

from enterprise_sim.authoring.sdk import (
    Activation,
    Declares,
    Deliverable,
    EmittedEvent,
    OnStart,
    Playbook,
    Process,
    Role,
    Selector,
    Step,
)
from enterprise_sim.core.registry import PLAYBOOKS, PROCESSES


def _lead() -> Role:
    """The person who runs this work (any Person — narrow the selector as needed)."""
    return Role(
        name="lead",
        select=Selector(type="Person", count=1),
        description="Runs the {title} work.",
    )


def kickoff() -> Process:
    """Kick the {title} work off (``OnStart``)."""
    return Process(
        name="{slug}_kickoff",
        description="Kick off the {title} work.",
        roles=(_lead(),),
        steps=(
            Step(
                id="kickoff",
                by="lead",
                at="day 0",
                duration="1d",
                emits=(
                    EmittedEvent("{pascal}KickedOff", payload={{"intent": "start the work"}}),
                ),
                produces=Deliverable("{slug}_brief", "document"),
            ),
        ),
        declares=Declares(events=("{pascal}KickedOff",), deliverables=("{slug}_brief",)),
    )


def {slug}_playbook() -> Playbook:
    """The {title} playbook: a single kickoff step. Add more activations as needed."""
    return Playbook(
        name="{slug}_playbook",
        vertical="{slug}",
        goal_template="Deliver {{project}} through the {title} playbook.",
        roles=(_lead(),),
        activations=(
            Activation(
                id="kickoff_on_start",
                process=kickoff(),
                trigger=OnStart(),
                anchor="anchor:{slug}",
            ),
        ),
        deliverable_expectations=("{slug}_brief",),
    )


@dataclass(slots=True)
class _PlaybookPlugin:
    """Bridges the SDK ``Playbook`` to the registry protocol (see build_software.py)."""

    name: str
    vertical: str
    deliverables: Sequence[str]
    build: Callable[[], Playbook]


@dataclass(slots=True)
class _ProcessPlugin:
    """Bridges the SDK ``Process`` to the registry protocol (see build_software.py)."""

    name: str
    emits: Sequence[str]
    requests: Sequence[str]
    build: Callable[[], Process]


def _register() -> _PlaybookPlugin:
    for factory in (kickoff,):
        process = factory()
        PROCESSES.register(
            _ProcessPlugin(
                name=process.name,
                emits=process.declares.events,
                requests=process.declares.deliverables,
                build=factory,
            )
        )
    playbook = {slug}_playbook()
    plugin = _PlaybookPlugin(
        name=playbook.name,
        vertical=playbook.vertical,
        deliverables=playbook.deliverable_expectations,
        build={slug}_playbook,
    )
    PLAYBOOKS.register(plugin)
    return plugin


#: The registered playbook plugin (registration fires on import).
{slug.upper()}_PLAYBOOK = _register()
'''


def _playbook_test(slug: str) -> str:
    return f'''"""Tests for the "{slug}" playbook template."""

from __future__ import annotations

from pathlib import Path

from enterprise_sim.authoring import assert_conforms, check_playbook, run_playbook
from enterprise_sim.core.registry import PLAYBOOKS, discover_paths


def test_{slug}_playbook_lints_and_conforms() -> None:
    discover_paths([Path(__file__).resolve().parent.parent])
    plugin = PLAYBOOKS.get("{slug}_playbook")
    playbook = plugin.build()  # type: ignore[attr-defined]

    assert check_playbook(playbook) == []
    result = run_playbook(playbook, seed=1)
    assert_conforms(result)
'''


def _bundle_plugin(slug: str, description: str) -> str:
    title = _title(slug)
    pascal = _pascal(slug)
    return f'''"""The "{title}" bundle template: a department archetype + its own playbook.

Generated by ``enterprise-sim templates scaffold --kind bundle``
(EXPLORER_TEMPLATES.md §2.2). Edit freely — re-check with
``enterprise-sim templates validate --dir <templates-dir> --slug {slug}``.

{description or f"A minimal department + playbook pair for {title}."}
"""

from __future__ import annotations

from collections.abc import Callable, Sequence
from dataclasses import dataclass

from enterprise_sim.archetypes._base import DepartmentArchetypeSpec, TeamShape
from enterprise_sim.authoring.sdk import (
    Activation,
    Declares,
    Deliverable,
    EmittedEvent,
    OnStart,
    Playbook,
    Process,
    Role,
    Selector,
    Step,
)
from enterprise_sim.core.registry import ARCHETYPES, PLAYBOOKS, PROCESSES


def _lead() -> Role:
    """The person who runs this work (any Person — narrow the selector as needed)."""
    return Role(
        name="lead",
        select=Selector(type="Person", count=1),
        description="Runs the {title} work.",
    )


def kickoff() -> Process:
    """Kick the {title} work off (``OnStart``)."""
    return Process(
        name="{slug}_kickoff",
        description="Kick off the {title} work.",
        roles=(_lead(),),
        steps=(
            Step(
                id="kickoff",
                by="lead",
                at="day 0",
                duration="1d",
                emits=(
                    EmittedEvent("{pascal}KickedOff", payload={{"intent": "start the work"}}),
                ),
                produces=Deliverable("{slug}_brief", "document"),
            ),
        ),
        declares=Declares(events=("{pascal}KickedOff",), deliverables=("{slug}_brief",)),
    )


def {slug}_playbook() -> Playbook:
    """The {title} playbook: a single kickoff step. Add more activations as needed."""
    return Playbook(
        name="{slug}_playbook",
        vertical="{slug}",
        goal_template="Deliver {{project}} through the {title} playbook.",
        roles=(_lead(),),
        activations=(
            Activation(
                id="kickoff_on_start",
                process=kickoff(),
                trigger=OnStart(),
                anchor="anchor:{slug}",
            ),
        ),
        deliverable_expectations=("{slug}_brief",),
    )


@dataclass(slots=True)
class _PlaybookPlugin:
    """Bridges the SDK ``Playbook`` to the registry protocol (see build_software.py)."""

    name: str
    vertical: str
    deliverables: Sequence[str]
    build: Callable[[], Playbook]


@dataclass(slots=True)
class _ProcessPlugin:
    """Bridges the SDK ``Process`` to the registry protocol (see build_software.py)."""

    name: str
    emits: Sequence[str]
    requests: Sequence[str]
    build: Callable[[], Process]


def _register_playbook() -> _PlaybookPlugin:
    for factory in (kickoff,):
        process = factory()
        PROCESSES.register(
            _ProcessPlugin(
                name=process.name,
                emits=process.declares.events,
                requests=process.declares.deliverables,
                build=factory,
            )
        )
    playbook = {slug}_playbook()
    plugin = _PlaybookPlugin(
        name=playbook.name,
        vertical=playbook.vertical,
        deliverables=playbook.deliverable_expectations,
        build={slug}_playbook,
    )
    PLAYBOOKS.register(plugin)
    return plugin


#: The registered playbook plugin (registration fires on import).
{slug.upper()}_PLAYBOOK = _register_playbook()

#: The {title} department archetype, running its own {slug}_playbook.
{slug.upper()} = ARCHETYPES.register(
    DepartmentArchetypeSpec(
        name="{slug}",
        charter={(description or f"Run the {title} department.")!r},
        typical_goals=(
            "Ship {{project}} to general availability.",
        ),
        team_shapes=(
            TeamShape(title="{title} Core", count="2..5", skills=("generalist",)),
        ),
        playbooks=("{slug}_playbook",),
    )
)
'''


def _bundle_test(slug: str) -> str:
    return f'''"""Tests for the "{slug}" bundle template."""

from __future__ import annotations

from pathlib import Path

from enterprise_sim.authoring import assert_conforms, check_playbook, run_playbook
from enterprise_sim.core.registry import ARCHETYPES, PLAYBOOKS, discover_paths


def test_{slug}_bundle_registers_and_conforms() -> None:
    discover_paths([Path(__file__).resolve().parent.parent])

    spec = ARCHETYPES.get("{slug}")
    assert spec.playbooks == ("{slug}_playbook",)

    plugin = PLAYBOOKS.get("{slug}_playbook")
    playbook = plugin.build()  # type: ignore[attr-defined]
    assert check_playbook(playbook) == []
    result = run_playbook(playbook, seed=1)
    assert_conforms(result)
'''


def scaffold(
    templates_dir: Path,
    *,
    slug: str,
    kind: TemplateKind | str,
    name: str,
    description: str = "",
) -> Template:
    """Write ``<templates_dir>/<slug>/`` (``template.json`` + ``plugin.py`` + test).

    Raises :class:`FileExistsError` if the template directory already exists,
    and :class:`ValueError` for a malformed ``slug``. Returns the written
    (``unvalidated``) :class:`~enterprise_sim.templates.store.Template`.
    """
    _validate_slug(slug)
    kind = TemplateKind(kind)
    directory = template_dir(templates_dir, slug)
    if directory.exists():
        raise FileExistsError(f"template {slug!r} already exists at {directory}")
    directory.mkdir(parents=True)

    if kind is TemplateKind.DEPARTMENT:
        plugin_source = _department_plugin(slug, description)
        test_source = _department_test(slug)
    elif kind is TemplateKind.PLAYBOOK:
        plugin_source = _playbook_plugin(slug, description)
        test_source = _playbook_test(slug)
    else:
        plugin_source = _bundle_plugin(slug, description)
        test_source = _bundle_test(slug)

    (directory / "plugin.py").write_text(plugin_source, encoding="utf-8")
    (directory / f"test_{slug}.py").write_text(test_source, encoding="utf-8")

    stamp = now_iso()
    template = Template(
        slug=slug,
        name=name,
        kind=kind,
        description=description,
        created_at=stamp,
        updated_at=stamp,
    )
    write_template(templates_dir, template)
    return template


__all__ = ["scaffold"]
